### PR TITLE
the template path fix for windows

### PR DESCRIPTION
**Pull request by nuclon**
Fix for #1

### CODE REVIEW

**Comment by nuclon** [comment]
One check has failed because of the network problem. Could you rerun the checks?

**Comment by riponbanik** [comment]
@nuclon for Windows, default value is available from below,

https://github.com/riponbanik/ansible-role-aws-cloudwatch-agent/blob/master/vars/Windows.yml

Which by default will be available from https://github.com/riponbanik/ansible-role-aws-cloudwatch-agent/tree/master/templates

Custom file can also be set be specifying the path in your playbook folder instead of using default.

**Comment by nuclon** [comment]
@riponbanik , see #1 -
It is not possible to overwrite template path variable in the playbook if running under windows.
The reason is the variable in role vars has higher priority than playbook variables.

**Comment by nuclon** [comment]
So even if I have
`aws_cw_config_template_path: templates/cw-logs.windows.json.j2`
in my group or host vars, the variable is still has value of "agent-config-windows.json.j2" on playbook running.

**Comment by nuclon** [comment]
see https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

**Comment by riponbanik** [comment]
@nuclon Running Ansible under Windows is not supported, Windows should be the target server. Also what is the issue to place it as role variable like below?

- hosts: all
  roles:
    -  role: riponbanik.aws-cloudwatch-agent
       aws_cw_config_template_path: templates/cw-logs.windows.json.j2

**Pull request closed without merging**
